name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🛠️ Build Angular app
        run: npm run build -- --configuration production

      - name: 🧹 Limpiar carpeta destino en el VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            rm -rf /var/www/frontend/rpvai.com/*

      - name: 🚀 Deploy al servidor VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: "dist/landing-page-rpv/browser"
          target: "/var/www/frontend/rpvai.com"

      - name: 📜 Ejecutar script post-deploy (opcional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            echo "✅ Frontend actualizado correctamente"
